name: "DaveN"
picture: "assets/img/picture.jpg"
bio: "give me money"
meta:
  lang: "en"
  description: "give me money"
  title: "DaveN"
  author: "DaveN"
  siteUrl: "https://xdaven.github.io/donate/"
links:
  - name: "PayPal"
    url: "https://paypal.me/manlikedaven"
  - name: "Revolut"
    url: "https://revolut.me/xdaven"
crypto_wallets:
  - name: "Bitcoin"
    address: "bc1qwfpz2207enlt9s4zwpu6c2edv0dfelm2lf9q5q"
  - name: "Monero"
    address: "8ARMrc5NWyuETHqgimgx3FhSaxWrnzxAgVqm1Jd3UV9d8sw4CCJMniJ14a3X9GsXY6eBFATpAFVk2GLpH7HPXi8VGbGrvyF"
  - name: "Solana"
    address: "FmJkh7JiKkjzyNqsvDJBrwuGYDCJzDhuWGTkJBdYb8kq"
theme: "custom"